##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  项目启动端口  ###################
server:
  port: 8080
  servlet:
    context-path: /s
#  tomcat:
#    basedir: /Users/wigo/工作目录/项目集合/榜单生成/tmp
