# Uncomment this line to define a global platform for your project
platform :ios, '13.0'
use_frameworks! 


target ‘ListDemo’ do
    
    pod 'BBSwiftUIKit'
    pod 'SDWebImageSwiftUI'
#    pod 'FGSwiftUIImage'


end
