server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    fetch-registry: true
    register-with-eureka: true
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000
spring:
  application:
    name: cloud-ShortURL-consumer
