server:
  port: 8911
  tomcat:
    threads:
      max: 1000
    max-connections: 200
    accept-count: 20
  servlet:
    session:
      timeout: 100

domain:
  short:
    check: false
    length: 8    #短域名长度
  localMapMaxNum: 100000000    #本地数据最大限制





