/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 26 11:24:43 GMT 2021
 */

package com.sunjinghao.shorturl.common.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.sunjinghao.shorturl.common.result.GlobalHttpResult;
import com.sunjinghao.shorturl.common.result.GlobalResultCodeEnum;
import com.sunjinghao.shorturl.common.util.GlobalHttpResultUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GlobalHttpResultUtil_ESTest extends GlobalHttpResultUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Integer integer0 = new Integer((-2149));
      // Undeclared exception!
      try { 
        GlobalHttpResultUtil.createResult((GlobalResultCodeEnum) null, integer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.sunjinghao.shorturl.common.result.GlobalHttpResult", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      // Undeclared exception!
      try { 
        GlobalHttpResultUtil.createResult((GlobalResultCodeEnum) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.sunjinghao.shorturl.common.result.GlobalHttpResult", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GlobalHttpResult<Object> globalHttpResult0 = GlobalHttpResultUtil.error("'Y7DD0]E_Ewe");
      assertEquals("'Y7DD0]E_Ewe", globalHttpResult0.getMessage());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GlobalHttpResult<String> globalHttpResult0 = GlobalHttpResultUtil.success();
      assertEquals(200, (int)globalHttpResult0.getCode());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GlobalHttpResult<String> globalHttpResult0 = GlobalHttpResultUtil.success("'Y7DD0]E_Ewe");
      assertEquals(200, (int)globalHttpResult0.getCode());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GlobalHttpResultUtil globalHttpResultUtil0 = new GlobalHttpResultUtil();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GlobalHttpResult<Object> globalHttpResult0 = GlobalHttpResultUtil.businessSuccess((Object) "'Y7DD0]E_Ewe", "'Y7DD0]E_Ewe");
      assertEquals("'Y7DD0]E_Ewe", globalHttpResult0.getMessage());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GlobalHttpResult<Object> globalHttpResult0 = GlobalHttpResultUtil.createResult((Integer) null, "'Y7DD0]E_Ewe");
      assertEquals("'Y7DD0]E_Ewe", globalHttpResult0.getMessage());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GlobalResultCodeEnum globalResultCodeEnum0 = GlobalResultCodeEnum.DATA_ERROR;
      GlobalHttpResult<String> globalHttpResult0 = GlobalHttpResultUtil.createResult(globalResultCodeEnum0);
      assertEquals("\u8BF7\u6C42\u5931\u8D25", globalHttpResult0.getMessage());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GlobalHttpResult<String> globalHttpResult0 = GlobalHttpResultUtil.success("'Y7DD0]E_Ewe");
      assertEquals("'Y7DD0]E_Ewe", globalHttpResult0.getMessage());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GlobalResultCodeEnum globalResultCodeEnum0 = GlobalResultCodeEnum.DATA_ERROR;
      GlobalHttpResult<Object> globalHttpResult0 = GlobalHttpResultUtil.createResult(globalResultCodeEnum0, (Object) globalResultCodeEnum0);
      assertEquals(999, (int)globalHttpResult0.getCode());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GlobalHttpResult<String> globalHttpResult0 = GlobalHttpResultUtil.error(0, "'Y7DD0]E_Ewe");
      assertEquals(0, (int)globalHttpResult0.getCode());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GlobalHttpResult<Object> globalHttpResult0 = GlobalHttpResultUtil.paramError((Object) null);
      assertEquals("\u975E\u6CD5\u7684\u8BF7\u6C42\u53C2\u6570", globalHttpResult0.getMessage());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GlobalHttpResult<Object> globalHttpResult0 = GlobalHttpResultUtil.error();
      assertEquals(500, (int)globalHttpResult0.getCode());
  }
}
