/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 26 11:18:44 GMT 2021
 */

package com.sunjinghao.shorturl.common.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.sunjinghao.shorturl.common.util.NumberEncodeUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NumberEncodeUtil_ESTest extends NumberEncodeUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      NumberEncodeUtil.numberEncryptToStr(922337203685477580L, 10);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      // Undeclared exception!
      try { 
        NumberEncodeUtil.numberEncryptToStr(3947L, (-956));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 123
         //
         verifyException("com.sunjinghao.shorturl.common.util.NumberEncodeUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Long long0 = new Long((-935L));
      NumberEncodeUtil.encryptNumber(long0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Long long0 = new Long(0L);
      Long long1 = NumberEncodeUtil.encryptNumber(long0);
      NumberEncodeUtil.encryptNumber(long1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Long long0 = new Long((-1077L));
      NumberEncodeUtil.decodeNumber(long0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Long long0 = new Long(0L);
      Long long1 = NumberEncodeUtil.encryptNumber(long0);
      NumberEncodeUtil.decodeNumber(long1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Long long0 = new Long(0L);
      NumberEncodeUtil.decodeNumber(long0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      NumberEncodeUtil.strToNumber("com.sunjinghao.shorturl.common.util.NumberEncodeUtil", 77);
      NumberEncodeUtil.strToNumber("com.sunjinghao.shorturl.common.util.NumberEncodeUtil", 77);
      NumberEncodeUtil.strToNumber("com.sunjinghao.shorturl.common.util.NumberEncodeUtil", 29);
      NumberEncodeUtil.strToNumber("1i", 61);
      // Undeclared exception!
      NumberEncodeUtil.strToNumber("1i", 29);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        NumberEncodeUtil.strToNumber("", 10);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        NumberEncodeUtil.strToNumber((String) null, 11);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.sunjinghao.shorturl.common.util.NumberEncodeUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try { 
        NumberEncodeUtil.numberEncryptToStr((-1L), 676);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 619
         //
         verifyException("com.sunjinghao.shorturl.common.util.NumberEncodeUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try { 
        NumberEncodeUtil.numberEncryptToStr(0L, 0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("com.sunjinghao.shorturl.common.util.NumberEncodeUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        NumberEncodeUtil.encryptNumber((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.sunjinghao.shorturl.common.util.NumberEncodeUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      // Undeclared exception!
      try { 
        NumberEncodeUtil.decodeNumber((Long) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.sunjinghao.shorturl.common.util.NumberEncodeUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      long long0 = NumberEncodeUtil.strToNumber("X", (-2067));
      assertEquals(59L, long0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      long long0 = NumberEncodeUtil.strToNumber("", 3521);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      NumberEncodeUtil numberEncodeUtil0 = new NumberEncodeUtil();
  }
}
