/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 26 11:21:27 GMT 2021
 */

package com.sunjinghao.shorturl.common.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sunjinghao.shorturl.common.result.RpcResult;
import com.sunjinghao.shorturl.common.util.RpcResultUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RpcResultUtil_ESTest extends RpcResultUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RpcResultUtil rpcResultUtil0 = new RpcResultUtil();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RpcResult<Object> rpcResult0 = RpcResultUtil.error("com.sunjinghao.shorturl.common.util.RpcResultUtil");
      assertEquals(500, (int)rpcResult0.getCode());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Object object0 = new Object();
      RpcResult<Object> rpcResult0 = RpcResultUtil.success(object0);
      assertEquals("\u8BF7\u6C42\u6210\u529F", rpcResult0.getMsg());
  }
}
