# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LHAppListDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for LHAppListDemo

  pod 'Moya', '~> 15.0'

end

target 'LHAppListDemoTests' do
  
  pod 'Moya', '~> 15.0'
  
end
