spring:
  application:
    name: ${APP_NAME:xurl}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  tomcat:
    accesslog:
      # 线上需正确配置日志
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:
    threads:
      min-spare: 10 # 设置为cpu核数
      max: 10 # # 设置为cpu核数

xurl:
  short-domain: sqc.cn
  machine-no: 0
