server:
  port: 8081
  use-forward-headers: true
  tomcat:
    max-threads: 500
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'
      directory: @log_path@
      prefix: access
    basedir: @log_path@
  servlet:
    session:
      timeout: P1D  #1天过期
      cookie:
        path: /
    context-path: /api

spring:
  application:
    name: domain-service
  jackson:
    default-property-inclusion: non_null
  servlet:
    # 多文件上传文件最大限制设置
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB
  aop:
    proxy-target-class: true
  data:
      redis:
        repositories:
          enabled: false
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
#    username: test
#    password: test
#    hikari:
#      connection-timeout: 20000
#      maximum-pool-size: 200
#      minimum-idle: 10
#      idle-timeout: 60000
#      connection-init-sql: set names utf8mb4;
#  redis:
#    database: 0
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0
#    timeout: 10000
#    cluster:
#      nodes:
#        - staging01.bj:6380
#        - staging02.bj:6381
  session:
    store-type: none
#    redis:
#      flush-mode: on_save
#      namespace: spring:session

reissue-batch-size: 100

logging:
  level:
    root: INFO
    com.xiaomi: @log4j_level@
  file: @log_path@/${spring.application.name}.log

domain:
  cacheSeconds: 3600
  step: 10000
