# 应用名称
server:
    port: 8080
    servlet:
       context-path: /transfer
       
spring:
  swagger:
    enabled: true
    title: spring-boot-swagger
    base-package: com.example.demo.controller 
    description: demo
    version: 1.0.0-SNAPSHOT 