// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "DemoApp",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "DemoApp",
            targets: ["AppModule"],
            bundleIdentifier: "com.miejoy.DemoApp",
            teamIdentifier: "2QLCT7DGXB",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://gogs.miejoy.com:4443/Swift/MJWebInterface", .branch("master")),
        .package(url: "https://gogs.miejoy.com:4443/Swift/MJDataFlow", .branch("master"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "MJWebInterface", package: "mjwebinterface"),
                .product(name: "MJDataFlow", package: "mjdataflow")
            ],
            path: "."
        )
    ]
)