package com.example.shortUrl.domain.po;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ShortUrl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_url.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_url.base_url
     *
     * @mbggenerated
     */
    private String baseUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_url.short_code
     *
     * @mbggenerated
     */
    private String shortCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_url.full_url
     *
     * @mbggenerated
     */
    private String fullUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_url.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_url.expiration_time
     *
     * @mbggenerated
     */
    private Date expirationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_url.id
     *
     * @return the value of short_url.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_url.id
     *
     * @param id the value for short_url.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_url.base_url
     *
     * @return the value of short_url.base_url
     *
     * @mbggenerated
     */
    public String getBaseUrl() {
        return baseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_url.base_url
     *
     * @param baseUrl the value for short_url.base_url
     *
     * @mbggenerated
     */
    public void setBaseUrl(String baseUrl) {
        this.baseUrl = baseUrl == null ? null : baseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_url.short_code
     *
     * @return the value of short_url.short_code
     *
     * @mbggenerated
     */
    public String getShortCode() {
        return shortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_url.short_code
     *
     * @param shortCode the value for short_url.short_code
     *
     * @mbggenerated
     */
    public void setShortCode(String shortCode) {
        this.shortCode = shortCode == null ? null : shortCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_url.full_url
     *
     * @return the value of short_url.full_url
     *
     * @mbggenerated
     */
    public String getFullUrl() {
        return fullUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_url.full_url
     *
     * @param fullUrl the value for short_url.full_url
     *
     * @mbggenerated
     */
    public void setFullUrl(String fullUrl) {
        this.fullUrl = fullUrl == null ? null : fullUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_url.create_time
     *
     * @return the value of short_url.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_url.create_time
     *
     * @param createTime the value for short_url.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_url.expiration_time
     *
     * @return the value of short_url.expiration_time
     *
     * @mbggenerated
     */
    public Date getExpirationTime() {
        return expirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_url.expiration_time
     *
     * @param expirationTime the value for short_url.expiration_time
     *
     * @mbggenerated
     */
    public void setExpirationTime(Date expirationTime) {
        this.expirationTime = expirationTime;
    }
}