server:
  port: 8088
spring:
  application:
    name: interview-assignments-boot
  redis:
    host: localhost
    port: 6379
    password: root
    lettuce:
      pool:
       maxActive: 8  # 连接池最大连接数（使用负值表示没有限制）
       maxWait: 800 # 连接池最大阻塞等待时间（使用负值表示没有限制）
       maxIdle: 8 # 连接池中的最大空闲连接
       minIdle: 2 # 连接池中的最小空闲连接
    timeout: 2000 # 连接或读取超时时长（毫秒）
logging:
  config: classpath:logback-spring.xml
short:
  url:
   timeout: 10
   userCacheName : shortUrlCache