server:
  port: 8088
spring:
  application:
    name: interview-assignments-boot
  redis:
    host: localhost
    port: 6379
    password: root
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
logging:
  config: classpath:logback-spring.xml
short:
  url:
   timeout: 10
   userCacheName : shortUrlCache

# 连接池最大连接数(使用负值表示没有限制) 默认为8
#spring.redis.lettuce.pool.max-active=8
# 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
#spring.redis.lettuce.pool.max-wait=-1ms
# 连接池中的最大空闲连接 默认为8
#spring.redis.lettuce.pool.max-idle=8
# 连接池中的最小空闲连接 默认为 0
#spring.redis.lettuce.pool.min-idle=0