package com.example.assignment.dao;

import com.example.assignment.dto.UrlRecord;
import com.example.assignment.dto.UrlRecordCriteria;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UrlRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_record
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    long countByExample(UrlRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_record
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    int deleteByExample(UrlRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_record
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_record
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    int insert(UrlRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_record
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    long insertSelective(UrlRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_record
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    List<UrlRecord> selectByExample(UrlRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_record
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    UrlRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_record
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    int updateByExampleSelective(@Param("record") UrlRecord record, @Param("example") UrlRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_record
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    int updateByExample(@Param("record") UrlRecord record, @Param("example") UrlRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_record
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    int updateByPrimaryKeySelective(UrlRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_record
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    int updateByPrimaryKey(UrlRecord record);
}