version: "3.1"

services:
  redis:
    image: redis
    container_name: demo_redis
    environment:
      TZ: Asia/Shanghai
    ports: 
      - 6379:6379
    volumes: 
      - ./redis_conf:/etc/redis/
      - ./redis_data:/data
    command: 
      redis-server /etc/redis/redis.conf
    restart: always
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
          
  postgres:
    image: postgres:12-alpine
    container_name: demo_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
