/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Oct 26 11:35:21 GMT 2021
 */

package com.sunjinghao.shorturl.gateway;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class ShortUrlApplication_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.sunjinghao.shorturl.gateway.ShortUrlApplication"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "GBK"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "CN"); 
    java.lang.System.setProperty("user.dir", "F:\\java-code\\shorturl-project\\short-url-gateway"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Administrator"); 
    java.lang.System.setProperty("user.language", "zh"); 
    java.lang.System.setProperty("user.name", "Administrator"); 
    java.lang.System.setProperty("user.timezone", "Asia/Shanghai"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ShortUrlApplication_ESTest_scaffolding.class.getClassLoader() ,
      "org.springframework.util.ReflectionUtils$FieldFilter",
      "org.springframework.aop.support.AopUtils",
      "org.springframework.boot.context.event.ApplicationReadyEvent",
      "org.springframework.boot.SpringApplicationShutdownHook$ApplicationContextClosedListener",
      "org.springframework.context.ApplicationContextException",
      "org.springframework.context.event.SimpleApplicationEventMulticaster",
      "org.springframework.boot.SpringApplicationShutdownHook$Handlers",
      "org.springframework.core.annotation.AnnotationTypeMapping",
      "org.springframework.boot.context.event.ApplicationStartedEvent",
      "org.springframework.context.ApplicationEventPublisher",
      "org.springframework.boot.logging.logback.LogbackLoggingSystem",
      "org.springframework.core.io.Resource",
      "org.springframework.boot.logging.log4j2.Log4J2LoggingSystem",
      "org.springframework.util.ClassUtils",
      "org.springframework.util.StopWatch",
      "org.springframework.core.PriorityOrdered",
      "org.springframework.core.metrics.ApplicationStartup",
      "org.springframework.boot.SpringApplicationRunListeners",
      "org.springframework.beans.factory.support.BeanNameGenerator",
      "org.springframework.core.annotation.AnnotationAwareOrderComparator",
      "org.springframework.context.ApplicationContextAware",
      "org.springframework.core.Ordered",
      "org.springframework.boot.BootstrapRegistry",
      "org.springframework.core.env.CommandLinePropertySource",
      "org.springframework.util.ConcurrentReferenceHashMap$Entry",
      "org.springframework.boot.ApplicationArguments",
      "org.springframework.boot.context.properties.bind.Bindable$BindRestriction",
      "org.springframework.boot.context.config.DelegatingApplicationContextInitializer",
      "org.springframework.core.env.ConfigurablePropertyResolver",
      "org.springframework.util.ConcurrentReferenceHashMap$TaskOption",
      "org.springframework.core.ResolvableTypeProvider",
      "org.springframework.core.annotation.AnnotationsScanner",
      "org.springframework.boot.BootstrapRegistryInitializer",
      "org.springframework.util.ConcurrentReferenceHashMap",
      "org.springframework.core.annotation.RepeatableContainers$NoRepeatableContainers",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName",
      "org.springframework.beans.factory.BeanFactoryAware",
      "org.springframework.core.env.EnvironmentCapable",
      "org.springframework.boot.autoconfigure.BackgroundPreinitializer",
      "org.springframework.core.annotation.AnnotationFilter$2",
      "org.springframework.boot.context.ContextIdApplicationContextInitializer",
      "org.springframework.context.event.AbstractApplicationEventMulticaster$DefaultListenerRetriever",
      "org.springframework.core.convert.ConversionService",
      "org.springframework.context.MessageSource",
      "org.springframework.core.annotation.AnnotationFilter$1",
      "org.springframework.boot.autoconfigure.EnableAutoConfiguration",
      "org.springframework.util.ConcurrentReferenceHashMap$Entries",
      "org.springframework.core.DecoratingProxy",
      "org.springframework.beans.BeansException",
      "org.springframework.core.annotation.RepeatableContainers$StandardRepeatableContainers",
      "org.springframework.context.annotation.ComponentScan",
      "org.springframework.core.annotation.AnnotationFilter",
      "org.springframework.core.annotation.MergedAnnotationSelectors$FirstDirectlyDeclared",
      "org.springframework.context.Lifecycle",
      "org.springframework.util.MultiValueMapAdapter",
      "org.springframework.context.ApplicationEvent",
      "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyNameException",
      "org.springframework.core.ResolvableType$1",
      "org.springframework.beans.factory.BeanFactory",
      "org.springframework.boot.WebApplicationType",
      "org.springframework.core.annotation.MergedAnnotationSelector",
      "org.springframework.boot.context.event.ApplicationPreparedEvent",
      "org.springframework.boot.ApplicationContextFactory",
      "org.springframework.core.annotation.MergedAnnotationSelectors",
      "org.springframework.boot.logging.DelegatingLoggingSystemFactory",
      "org.springframework.context.annotation.ComponentScan$Filter",
      "org.springframework.core.env.SimpleCommandLinePropertySource",
      "org.springframework.boot.SpringApplication",
      "org.springframework.core.io.support.PropertiesLoaderUtils",
      "org.springframework.core.annotation.AnnotationsProcessor",
      "org.springframework.context.ConfigurableApplicationContext",
      "org.springframework.core.SpringProperties",
      "org.springframework.boot.logging.DeferredLogFactory",
      "org.springframework.core.annotation.AttributeMethods",
      "org.springframework.context.event.ApplicationEventMulticaster",
      "org.springframework.boot.logging.logback.LogbackLoggingSystem$Factory",
      "org.springframework.core.annotation.PackagesAnnotationFilter",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName$ElementType",
      "org.springframework.boot.context.properties.bind.Bindable",
      "org.springframework.aop.AopInvocationException",
      "org.springframework.core.NestedRuntimeException",
      "org.springframework.core.io.ResourceLoader",
      "org.springframework.boot.web.context.ServerPortInfoApplicationContextInitializer",
      "org.springframework.boot.env.EnvironmentPostProcessorApplicationListener",
      "org.springframework.boot.logging.LoggingSystemFactory",
      "org.springframework.core.LocalVariableTableParameterNameDiscoverer",
      "org.springframework.boot.env.EnvironmentPostProcessorsFactory",
      "org.springframework.boot.ClearCachesApplicationListener",
      "org.springframework.core.env.Environment",
      "org.springframework.core.ResolvableType$VariableResolver",
      "org.springframework.boot.logging.log4j2.Log4J2LoggingSystem$Factory",
      "org.springframework.util.ConcurrentReferenceHashMap$SoftEntryReference",
      "org.springframework.beans.BeanUtils",
      "org.springframework.beans.BeanInstantiationException",
      "org.springframework.core.io.UrlResource",
      "org.springframework.context.annotation.EnableAspectJAutoProxy",
      "org.springframework.boot.autoconfigure.SharedMetadataReaderFactoryContextInitializer",
      "org.springframework.beans.factory.Aware",
      "org.springframework.asm.ClassVisitor",
      "org.springframework.boot.builder.ParentContextCloserApplicationListener",
      "org.springframework.aop.TargetClassAware",
      "org.springframework.context.event.AbstractApplicationEventMulticaster$ListenerCacheKey",
      "org.springframework.boot.logging.DeferredLog$Lines",
      "org.springframework.boot.logging.Slf4JLoggingSystem",
      "org.springframework.cache.annotation.EnableCaching",
      "org.springframework.context.event.ApplicationContextEvent",
      "org.springframework.context.event.AbstractApplicationEventMulticaster$CachedListenerRetriever",
      "org.springframework.context.event.GenericApplicationListener",
      "org.springframework.core.annotation.AliasFor",
      "org.springframework.beans.FatalBeanException",
      "org.springframework.core.LocalVariableTableParameterNameDiscoverer$ParameterNameDiscoveringVisitor",
      "org.springframework.boot.ConfigurableBootstrapContext",
      "org.springframework.core.ResolvableType$DefaultVariableResolver",
      "org.springframework.context.annotation.AdviceMode",
      "org.springframework.context.annotation.ScopedProxyMode",
      "org.springframework.boot.SpringApplicationRunListener",
      "org.springframework.core.annotation.MergedAnnotation",
      "org.springframework.core.annotation.MissingMergedAnnotation",
      "org.springframework.core.SerializableTypeWrapper",
      "org.springframework.core.ResolvableType$TypeVariablesVariableResolver",
      "org.springframework.boot.SpringApplicationShutdownHandlers",
      "org.springframework.core.annotation.RepeatableContainers",
      "org.springframework.context.event.ContextRefreshedEvent",
      "org.springframework.context.annotation.ScopeMetadataResolver",
      "org.springframework.util.ReflectionUtils",
      "org.springframework.core.io.support.ResourcePatternResolver",
      "org.springframework.core.annotation.MergedAnnotations$SearchStrategy",
      "org.springframework.context.ApplicationContextInitializer",
      "org.springframework.util.Assert",
      "org.springframework.core.ParameterNameDiscoverer",
      "org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener",
      "org.springframework.core.convert.support.ConfigurableConversionService",
      "org.springframework.boot.logging.DeferredLogs",
      "org.springframework.util.ErrorHandler",
      "org.springframework.core.metrics.DefaultApplicationStartup$DefaultStartupStep",
      "org.springframework.core.annotation.ValueExtractor",
      "org.springframework.core.env.PropertyResolver",
      "org.springframework.aop.framework.AopProxyUtils",
      "org.springframework.core.io.support.SpringFactoriesLoader",
      "org.springframework.boot.context.event.ApplicationContextInitializedEvent",
      "org.springframework.core.annotation.AnnotationConfigurationException",
      "org.springframework.core.convert.converter.ConverterRegistry",
      "org.springframework.core.PrioritizedParameterNameDiscoverer",
      "org.springframework.boot.SpringApplicationShutdownHook",
      "org.springframework.boot.rsocket.context.RSocketPortInfoApplicationContextInitializer",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName$ElementsParser",
      "org.springframework.boot.context.event.ApplicationStartingEvent",
      "org.springframework.core.env.CompositePropertySource",
      "org.springframework.util.CollectionUtils",
      "org.springframework.core.annotation.TypeMappedAnnotation",
      "org.springframework.core.io.InputStreamSource",
      "org.springframework.core.annotation.IntrospectionFailureLogger$1",
      "org.springframework.util.ConcurrentReferenceHashMap$Task",
      "org.springframework.core.annotation.IntrospectionFailureLogger$2",
      "org.springframework.beans.factory.ListableBeanFactory",
      "com.sunjinghao.shorturl.gateway.ShortUrlApplication",
      "org.springframework.core.annotation.AnnotationTypeMapping$MirrorSets$MirrorSet",
      "org.springframework.core.env.PropertySource",
      "org.springframework.context.event.GenericApplicationListenerAdapter",
      "org.springframework.aop.framework.Advised",
      "org.springframework.core.env.EnumerablePropertySource",
      "org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceManager",
      "org.springframework.context.event.ContextClosedEvent",
      "org.springframework.core.annotation.AnnotationTypeMappings",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceType",
      "org.springframework.core.KotlinDetector",
      "org.springframework.boot.context.event.ApplicationEnvironmentPreparedEvent",
      "org.springframework.core.env.ConfigurableEnvironment",
      "org.springframework.core.NativeDetector",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName$Elements",
      "org.springframework.boot.BootstrapContextClosedEvent",
      "springfox.documentation.swagger2.annotations.EnableSwagger2",
      "org.springframework.boot.context.FileEncodingApplicationListener",
      "org.springframework.core.ResolvableType$EmptyType",
      "org.springframework.util.ConcurrentReferenceHashMap$1",
      "org.springframework.util.ConcurrentReferenceHashMap$2",
      "org.springframework.util.ConcurrentReferenceHashMap$3",
      "org.springframework.boot.autoconfigure.SpringBootApplication",
      "org.springframework.util.ConcurrentReferenceHashMap$4",
      "org.springframework.aop.SpringProxy",
      "org.springframework.boot.ExitCodeEvent",
      "org.springframework.context.event.SmartApplicationListener",
      "org.springframework.beans.factory.config.BeanFactoryPostProcessor",
      "org.springframework.util.ObjectUtils",
      "org.springframework.context.annotation.Import",
      "org.springframework.util.MultiValueMap",
      "org.springframework.core.StandardReflectionParameterNameDiscoverer",
      "org.springframework.boot.logging.LogLevel",
      "org.springframework.core.OrderComparator",
      "org.springframework.util.ResourceUtils",
      "org.springframework.util.ReflectionUtils$MethodFilter",
      "org.springframework.boot.DefaultBootstrapContext",
      "org.springframework.boot.SpringBootConfiguration",
      "org.springframework.core.DefaultParameterNameDiscoverer",
      "org.springframework.util.ConcurrentReferenceHashMap$5",
      "org.springframework.util.LinkedMultiValueMap",
      "org.springframework.beans.factory.HierarchicalBeanFactory",
      "org.springframework.core.annotation.AnnotationTypeMappings$Cache",
      "org.springframework.core.annotation.AnnotationTypeMapping$MirrorSets",
      "org.springframework.boot.logging.LoggingSystem$NoOpLoggingSystem",
      "org.springframework.util.ConcurrentReferenceHashMap$Reference",
      "org.springframework.boot.context.config.DelegatingApplicationListener",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment",
      "org.springframework.boot.Banner$Mode",
      "org.springframework.core.annotation.MergedAnnotations",
      "org.springframework.boot.context.config.AnsiOutputApplicationListener",
      "org.springframework.core.ResolvableType$SyntheticParameterizedType",
      "org.springframework.core.annotation.MergedAnnotationSelectors$Nearest",
      "org.springframework.boot.context.event.EventPublishingRunListener",
      "org.springframework.core.ResolvableType",
      "org.springframework.core.annotation.RepeatableContainers$ExplicitRepeatableContainer",
      "org.springframework.core.metrics.StartupStep$Tags",
      "org.springframework.core.annotation.AnnotationsScanner$1",
      "org.springframework.web.context.WebApplicationContext",
      "org.springframework.context.ApplicationListener",
      "org.springframework.boot.context.event.ApplicationFailedEvent",
      "org.springframework.util.PropertiesPersister",
      "org.springframework.core.SerializableTypeWrapper$TypeProvider",
      "org.springframework.core.env.MapPropertySource",
      "org.springframework.context.annotation.AnnotationScopeMetadataResolver",
      "org.springframework.util.ConcurrentReferenceHashMap$Restructure",
      "org.springframework.beans.factory.BeanClassLoaderAware",
      "org.springframework.core.annotation.OrderUtils",
      "org.springframework.boot.context.logging.LoggingApplicationListener",
      "org.springframework.core.ResolvableType$WildcardBounds",
      "org.springframework.boot.BootstrapContext",
      "org.springframework.boot.logging.LoggingSystem",
      "org.springframework.boot.Bootstrapper",
      "org.springframework.core.annotation.TypeMappedAnnotations",
      "org.springframework.context.event.AbstractApplicationEventMulticaster",
      "com.github.xiaoymin.swaggerbootstrapui.annotations.EnableSwaggerBootstrapUI",
      "org.springframework.core.io.AbstractFileResolvingResource",
      "org.springframework.core.SerializableTypeWrapper$SerializableTypeProxy",
      "org.springframework.core.annotation.Order",
      "org.springframework.core.annotation.TypeMappedAnnotations$MergedAnnotationFinder",
      "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent",
      "org.springframework.core.metrics.DefaultApplicationStartup$DefaultStartupStep$DefaultTags",
      "org.springframework.core.annotation.IntrospectionFailureLogger",
      "org.springframework.core.metrics.DefaultApplicationStartup",
      "org.springframework.core.NestedIOException",
      "org.springframework.boot.availability.AvailabilityState",
      "org.springframework.core.metrics.StartupStep",
      "org.springframework.core.annotation.AbstractMergedAnnotation",
      "org.springframework.context.ApplicationContext",
      "org.springframework.web.context.ConfigurableWebApplicationContext",
      "org.springframework.core.io.AbstractResource",
      "org.springframework.boot.context.event.SpringApplicationEvent",
      "org.springframework.beans.factory.NoSuchBeanDefinitionException",
      "org.springframework.boot.logging.AbstractLoggingSystem",
      "org.springframework.util.StringUtils"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ShortUrlApplication_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.sunjinghao.shorturl.gateway.ShortUrlApplication",
      "org.springframework.context.annotation.ScopedProxyMode",
      "org.springframework.context.annotation.AdviceMode",
      "org.springframework.boot.SpringApplicationShutdownHook",
      "org.springframework.boot.SpringApplicationShutdownHook$Handlers",
      "org.springframework.boot.SpringApplicationShutdownHook$ApplicationContextClosedListener",
      "org.springframework.boot.SpringApplication",
      "org.springframework.boot.Banner$Mode",
      "org.springframework.boot.ApplicationContextFactory",
      "org.springframework.core.metrics.DefaultApplicationStartup$DefaultStartupStep",
      "org.springframework.core.metrics.DefaultApplicationStartup$DefaultStartupStep$DefaultTags",
      "org.springframework.core.metrics.DefaultApplicationStartup",
      "org.springframework.core.metrics.ApplicationStartup",
      "org.springframework.util.Assert",
      "org.springframework.boot.WebApplicationType",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceType",
      "org.springframework.util.ConcurrentReferenceHashMap",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceManager",
      "org.springframework.util.ClassUtils",
      "org.springframework.core.io.support.SpringFactoriesLoader",
      "org.springframework.util.ConcurrentReferenceHashMap$Restructure",
      "org.springframework.core.io.AbstractResource",
      "org.springframework.core.io.AbstractFileResolvingResource",
      "org.springframework.core.io.UrlResource",
      "org.springframework.core.SpringProperties",
      "org.springframework.core.io.support.PropertiesLoaderUtils",
      "org.springframework.util.ResourceUtils",
      "org.springframework.util.StringUtils",
      "org.springframework.util.CollectionUtils",
      "org.springframework.util.ConcurrentReferenceHashMap$Task",
      "org.springframework.util.ConcurrentReferenceHashMap$1",
      "org.springframework.util.ConcurrentReferenceHashMap$TaskOption",
      "org.springframework.util.ConcurrentReferenceHashMap$Entry",
      "org.springframework.util.ConcurrentReferenceHashMap$SoftEntryReference",
      "org.springframework.core.OrderComparator",
      "org.springframework.core.annotation.AnnotationAwareOrderComparator",
      "org.springframework.util.ObjectUtils",
      "org.springframework.core.PrioritizedParameterNameDiscoverer",
      "org.springframework.core.DefaultParameterNameDiscoverer",
      "org.springframework.core.KotlinDetector",
      "org.springframework.core.StandardReflectionParameterNameDiscoverer",
      "org.springframework.core.LocalVariableTableParameterNameDiscoverer",
      "org.springframework.beans.BeanUtils",
      "org.springframework.util.ReflectionUtils",
      "org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer",
      "org.springframework.boot.context.ContextIdApplicationContextInitializer",
      "org.springframework.boot.context.config.DelegatingApplicationContextInitializer",
      "org.springframework.boot.rsocket.context.RSocketPortInfoApplicationContextInitializer",
      "org.springframework.boot.web.context.ServerPortInfoApplicationContextInitializer",
      "org.springframework.boot.autoconfigure.SharedMetadataReaderFactoryContextInitializer",
      "org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener",
      "org.springframework.boot.logging.LogLevel",
      "org.springframework.core.annotation.MergedAnnotations$SearchStrategy",
      "org.springframework.core.annotation.RepeatableContainers",
      "org.springframework.core.annotation.RepeatableContainers$StandardRepeatableContainers",
      "org.springframework.core.annotation.PackagesAnnotationFilter",
      "org.springframework.core.annotation.AnnotationFilter$1",
      "org.springframework.core.annotation.AnnotationFilter$2",
      "org.springframework.core.annotation.AnnotationFilter",
      "org.springframework.core.annotation.RepeatableContainers$NoRepeatableContainers",
      "org.springframework.core.annotation.TypeMappedAnnotations",
      "org.springframework.core.annotation.AnnotationsScanner",
      "org.springframework.core.annotation.OrderUtils",
      "org.springframework.core.annotation.TypeMappedAnnotations$MergedAnnotationFinder",
      "org.springframework.core.annotation.MergedAnnotationSelectors$Nearest",
      "org.springframework.core.annotation.MergedAnnotationSelectors$FirstDirectlyDeclared",
      "org.springframework.core.annotation.MergedAnnotationSelectors",
      "org.springframework.core.annotation.AnnotationsScanner$1",
      "org.springframework.core.annotation.AbstractMergedAnnotation",
      "org.springframework.core.annotation.MissingMergedAnnotation",
      "org.springframework.boot.ClearCachesApplicationListener",
      "org.springframework.boot.builder.ParentContextCloserApplicationListener",
      "org.springframework.boot.context.FileEncodingApplicationListener",
      "org.springframework.boot.context.config.AnsiOutputApplicationListener",
      "org.springframework.boot.context.config.DelegatingApplicationListener",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName$Elements",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName$ElementsParser",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName$ElementType",
      "org.springframework.boot.context.properties.bind.Bindable$BindRestriction",
      "org.springframework.boot.context.properties.bind.Bindable",
      "org.springframework.core.ResolvableType$EmptyType",
      "org.springframework.core.ResolvableType",
      "org.springframework.core.SerializableTypeWrapper",
      "org.springframework.core.ResolvableType$SyntheticParameterizedType",
      "org.springframework.core.ResolvableType$TypeVariablesVariableResolver",
      "org.springframework.core.ResolvableType$DefaultVariableResolver",
      "org.springframework.util.MultiValueMapAdapter",
      "org.springframework.util.LinkedMultiValueMap",
      "org.springframework.boot.context.logging.LoggingApplicationListener",
      "org.springframework.boot.env.EnvironmentPostProcessorApplicationListener",
      "org.springframework.boot.logging.DeferredLogs",
      "org.springframework.boot.logging.DeferredLog$Lines",
      "org.springframework.core.NativeDetector",
      "org.springframework.boot.autoconfigure.BackgroundPreinitializer",
      "org.springframework.core.annotation.AttributeMethods",
      "org.springframework.core.annotation.IntrospectionFailureLogger",
      "org.springframework.core.annotation.AnnotationTypeMappings",
      "org.springframework.core.annotation.AnnotationTypeMappings$Cache",
      "org.springframework.core.annotation.AnnotationTypeMapping",
      "org.springframework.core.annotation.AnnotationTypeMapping$MirrorSets",
      "org.springframework.core.annotation.TypeMappedAnnotation",
      "org.springframework.util.StopWatch",
      "org.springframework.boot.DefaultBootstrapContext",
      "org.springframework.context.event.AbstractApplicationEventMulticaster",
      "org.springframework.context.event.SimpleApplicationEventMulticaster",
      "org.springframework.context.event.AbstractApplicationEventMulticaster$DefaultListenerRetriever",
      "org.springframework.boot.SpringApplicationRunListeners",
      "org.springframework.boot.context.event.EventPublishingRunListener",
      "org.springframework.aop.framework.AopProxyUtils",
      "org.springframework.context.ApplicationEvent",
      "org.springframework.boot.context.event.SpringApplicationEvent",
      "org.springframework.boot.context.event.ApplicationStartingEvent",
      "org.springframework.context.event.AbstractApplicationEventMulticaster$ListenerCacheKey",
      "org.springframework.context.event.AbstractApplicationEventMulticaster$CachedListenerRetriever",
      "org.springframework.context.event.GenericApplicationListenerAdapter",
      "org.springframework.core.ResolvableType$WildcardBounds",
      "org.springframework.aop.support.AopUtils",
      "org.springframework.boot.logging.DelegatingLoggingSystemFactory",
      "org.springframework.boot.logging.LoggingSystem",
      "org.springframework.boot.logging.logback.LogbackLoggingSystem$Factory"
    );
  }
}
