/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 26 11:35:21 GMT 2021
 */

package com.sunjinghao.shorturl.gateway;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.sunjinghao.shorturl.gateway.ShortUrlApplication;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ShortUrlApplication_ESTest extends ShortUrlApplication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        ShortUrlApplication.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unable to instantiate factory class [org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.Factory] for factory type [org.springframework.boot.logging.LoggingSystemFactory]
         //
         verifyException("org.springframework.core.io.support.SpringFactoriesLoader", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ShortUrlApplication shortUrlApplication0 = new ShortUrlApplication();
  }
}
