spring:
  datasource:
    url: jdbc:mysql://localhost:3306/short-demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 1000
        max-idle: 20
        min-idle: 2
    connect-timeout: 3000

mybatis:
  type-aliases-package: com.sxg.shortUrl.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
 