# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppStore

  pod 'YYModel', '1.0.4'

  target 'AppStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppStoreUITests' do
    # Pods for testing
  end

end
