export const container: string;
export const inner: string;
export const dots_container: string;
export const dots_outer: string;
export const dots_inner: string;
export const info_container: string;
export const info_text: string;
export const info_img: string;
export const carousel_item: string;
