# 项目信息
project:
  version: v1.0.0
  env: DEV
server:
  port: 8080
# Spring配置
spring:
  aop:
    proxy-target-class: true
  # redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 0
logging:
  config: classpath:log4j2.xml
  level:
    com.example: info

# Swagger配置
swagger:
  host:
  title: Project Swagger
  description:
  disabled: false # 是否禁用swagger
  redirect-uri: / # 禁用swagger时的重定向地址