@startuml
'转换短链

autonumber

http请求 -> 控制层: 获取短链(param：长链)
控制层 -> 服务层: 获取短链

服务层 -> 二级缓存: 查询短码
服务层 -> redis缓存: 查询短码

服务层 -> 转码引擎: 请求生成短码
转码引擎 --> 服务层: 返回短码

服务层 -> redis缓存: 保存短码
服务层 -> 二级缓存: 保存短码

服务层 --> 控制层: 返回短码
控制层 --> http请求: 返回短码

@enduml