/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 26 11:22:58 GMT 2021
 */

package com.sunjinghao.shorturl.common.aop;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.sunjinghao.shorturl.common.aop.LogAspect;
import java.lang.reflect.Method;
import org.aopalliance.intercept.MethodInvocation;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.springframework.aop.ProxyMethodInvocation;
import org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LogAspect_ESTest extends LogAspect_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LogAspect logAspect0 = new LogAspect();
      ProxyMethodInvocation proxyMethodInvocation0 = mock(ProxyMethodInvocation.class, new ViolatedAssumptionAnswer());
      doReturn((Method) null).when(proxyMethodInvocation0).getMethod();
      MethodInvocationProceedingJoinPoint methodInvocationProceedingJoinPoint0 = new MethodInvocationProceedingJoinPoint(proxyMethodInvocation0);
      // Undeclared exception!
      try { 
        logAspect0.doBefore(methodInvocationProceedingJoinPoint0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint$MethodSignatureImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LogAspect logAspect0 = new LogAspect();
      logAspect0.logPointCut();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LogAspect logAspect0 = new LogAspect();
      MethodInvocation methodInvocation0 = mock(MethodInvocation.class, new ViolatedAssumptionAnswer());
      doReturn(logAspect0).when(methodInvocation0).proceed();
      ProxyMethodInvocation proxyMethodInvocation0 = mock(ProxyMethodInvocation.class, new ViolatedAssumptionAnswer());
      doReturn(methodInvocation0).when(proxyMethodInvocation0).invocableClone();
      MethodInvocationProceedingJoinPoint methodInvocationProceedingJoinPoint0 = new MethodInvocationProceedingJoinPoint(proxyMethodInvocation0);
      try { 
        logAspect0.around(methodInvocationProceedingJoinPoint0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.sunjinghao.shorturl.common.aop.LogAspect", e);
      }
  }
}
