###

GET http://localhost:8000/YfTch

###

GET http://localhost:8000/api/v1/short/YfTch

###

POST http://localhost:8000/api/v1/short
Content-Type: application/json

{
  "url": "https://www.aa8i.com"
}