version: "3"

services:
  api-server:
    build:
      context: .
    container_name: api-server
    image: api-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://host.docker.internal:27017/links
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - "3000:3000"

networks:
  app-network:
    driver: bridge
