install! 'cocoapods', :warn_for_unused_master_specs_repo => false
use_frameworks!
inhibit_all_warnings!
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
#install! 'cocoapods', :disable_input_output_paths => true
#source 'https://github.com/CocoaPods/Specs.git'





target 'HSInterviewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'SVProgressHUD',            '2.2.5'
  pod 'Kingfisher',               '7.1.2'
  pod 'KingfisherWebP',           '1.4.0'
	pod 'SwiftyJSON',               '5.0.1'
	pod 'HandyJSON',                '5.0.2'
  pod 'BetterCodable',            '0.4.0'
  pod 'CSAPIService'
  pod 'BBSwiftUIKit'
  pod 'AsyncImage'
end

