server:
  port: 8080

spring:
  datasource:
    username: root
    password: Gino1986@
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.gc.shorturl.entity


#showSql
logging:
  level:
    com:
      example:
        mapper : debug