const WHITE_COLOR = '#fff';
const BLACK_COLOR = '#000';
const LIGHT_BLACK_COLOR = '#111111';
const LIGHT_GRAY_COLOR = '#FAFAFA'
const GRAY_COLOR = '#F1F1F1';

export { WHITE_COLOR, BLACK_COLOR, LIGHT_BLACK_COLOR, LIGHT_GRAY_COLOR, GRAY_COLOR}