package com.example.shortUrl.dao;

import com.example.shortUrl.domain.po.ShortUrl;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ShortUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_url
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_url
     *
     * @mbggenerated
     */
    int insert(ShortUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_url
     *
     * @mbggenerated
     */
    int insertSelective(ShortUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_url
     *
     * @mbggenerated
     */
    ShortUrl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_url
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShortUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_url
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShortUrl record);

    /**
     * @desc
     * @author shiqingshan
     * @Param [shortCode]
     * @Date 2021/5/20 下午12:51
     * @return com.example.shortUrl.domain.po.ShortUrl
    **/
    ShortUrl selectFullUrlByShortCode(@Param("shortCode")String shortCode);
}