# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#source 'https://github.com/CocoaPods/Specs.git'

target 'swiftUI-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftUI-demo
  pod 'Kingfisher'
pod 'SwiftyJSON'
  target 'swiftUI-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swiftUI-demoUITests' do
    # Pods for testing
  end

end
