---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 500Gi
