package com.example.assignment.dto;

import java.io.Serializable;
import java.util.Date;

public class UrlRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_record.id
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_record.long_url
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    private String longUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_record.create_time
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_record.update_time
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table url_record
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_record.id
     *
     * @return the value of url_record.id
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_record.id
     *
     * @param id the value for url_record.id
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_record.long_url
     *
     * @return the value of url_record.long_url
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    public String getLongUrl() {
        return longUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_record.long_url
     *
     * @param longUrl the value for url_record.long_url
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    public void setLongUrl(String longUrl) {
        this.longUrl = longUrl == null ? null : longUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_record.create_time
     *
     * @return the value of url_record.create_time
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_record.create_time
     *
     * @param createTime the value for url_record.create_time
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_record.update_time
     *
     * @return the value of url_record.update_time
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_record.update_time
     *
     * @param updateTime the value for url_record.update_time
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_record
     *
     * @mbg.generated Sat Jul 03 13:18:53 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", longUrl=").append(longUrl);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}