# Uncomment this line to define a global platform for your project
platform :ios, ’15.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'RefreshTableDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RefreshTableDemo
 
  pod 'Kingfisher'

end

