# Uncomment the next line to define a global platform for your project
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'InterviewiOSDemo' do

pod 'Alamofire'  
pod 'SDWebImage'

end
