#!/usr/bin/env bash

ROOT=`cd $(dirname $0)/;pwd`

SRC=$ROOT/src

SRCS=$(ls -l $SRC/ |awk '/^d/ {print $NF}')
for i in $SRCS
do
   tmp_dir=$SRC/$i
   GOPATH="$tmp_dir:$GOPATH"
done


Last_Char=${GOPATH: -1}
if [ "$Last_Char" = ":" ];then
   GOPATH=${GOPATH%?}
fi

export GOPATH=$GOPATH
export GOBIN=$ROOT/bin
export TMPDIR="/tmp"

OLD_IFS="$IFS"
IFS="/"
arr=($ROOT)
IFS="$OLD_IFS"

export CGO_ENABLED=0
export GOARCH=amd64
export GOOS=linux
cd "$SRC/main" && go build -o "$GOBIN/${arr[${#arr[*]}-1]}"
exit 0