<!doctype html>
<html  class="x-admin-sm">
<head>
	<meta charset="UTF-8">
	<title><?php echo $pageTitle;?></title>
	<meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <link rel="icon" href="data:;base64,=">
    <link rel="stylesheet" href="<?php echo $staticUrl; ?>css/font.css">
    <link rel="stylesheet" href="<?php echo $staticUrl; ?>css/login.css">
	  <link rel="stylesheet" href="<?php echo $staticUrl; ?>css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="<?php echo $staticUrl; ?>lib/layui/layui.js" charset="utf-8"></script>
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="login-bg">
    <?php echo $this->getContent(); ?>
</body>
</html>