/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 26 11:23:13 GMT 2021
 */

package com.sunjinghao.shorturl.common.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sunjinghao.shorturl.common.exception.MyException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MyException_ESTest extends MyException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MyException myException0 = new MyException("");
  }
}
