CREATE TABLE IF NOT EXISTS `short_url` (
	`id` INT UNSIGNED AUTO_INCREMENT,
	`url` TEXT NOT NULL,
	`hash` BIGINT UNSIGNED NOT NULL,
    `code` VARCHAR(10) NOT NULL DEFAULT '',
	`created_at` TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY (`id`),
    INDEX (hash)
) ENGINE = InnoDB CHARSET = utf8;

ALTER TABLE `short_url` AUTO_INCREMENT=5000;
