# 服务配置
server:
 port: 8080
knife4j:
  production: false #停用Swagger文档
spring:
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-active: 300
        max-wait: -1ms
        max-idle: 100
        min-idle: 0
