# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HJJSearchThird' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HJJSearchThird
  pod 'CocoaHTTPServer'
  
  target 'HJJSearchThirdTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HJJSearchThirdUITests' do
    # Pods for testing
  end

end
