server:
  port: 6300

logging:
  config:
    classpath: logback-spring.xml
  path: /logs/
  application:
    name: domain-convert
spring:
  application:
    name: domain-convert
  main:
    banner-mode: log
  jackson:
    time-zone: GMT+8
  profiles:
    include:
     - dev
    active: dev

mybatis-plus:
  global-config:
    banner: off





