## 参数配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/short_url?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root
shortUrl:
  generator:
    key: sqs
    baseUrl: https://tk.vip
# Mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.example.shortUrl.dao
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*.xml
