/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 26 11:22:12 GMT 2021
 */

package com.sunjinghao.shorturl.common.config;

import org.junit.Test;
import static org.junit.Assert.*;
import com.github.benmanes.caffeine.cache.Cache;
import com.sunjinghao.shorturl.common.config.CacheConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CacheConfig_ESTest extends CacheConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CacheConfig cacheConfig0 = new CacheConfig();
      Cache<String, Object> cache0 = cacheConfig0.caffeineCache();
      assertEquals(0L, cache0.estimatedSize());
  }
}
