/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 26 11:19:42 GMT 2021
 */

package com.sunjinghao.shorturl.common.config;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sunjinghao.shorturl.common.config.SwaggerConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import springfox.documentation.spring.web.plugins.Docket;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SwaggerConfig_ESTest extends SwaggerConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SwaggerConfig swaggerConfig0 = new SwaggerConfig();
      Docket docket0 = swaggerConfig0.createRestApi();
      assertEquals("default", docket0.getGroupName());
  }
}
