spring:
  application:
    name: domain-service
server:
  port: 8080

# ===== ???swagger?? ===== #
swagger:
  enable: true
  application-name: ????
  application-version: 1.0
  application-description: ??????
  try-host: http://localhost:${server.port}