#  兜底配置-假如未指定 环境变量：NODE_ENV=development/test/production 默认development的生效
port: 3000
# knex 加载数据库配置-参考： https://knexjs.org/guide/#configuration-options
dbConfig: { client: 'sqlite3', connection: { filename: './data.db' } }
# LRUCache 缓存配置 参考：https://github.com/isaacs/node-lru-cache#readme
cacheOptions: {
        #  最大数量
        max: 100,
        # ms
        ttl: 3600000,
        #  获取时更新存活时间
        updateAgeOnGet: true,
    }
# 短域名长度最大字符数（不含域名）
shortCodeMaxLength: 8
# 短域名部分
shortUrlPrefix: https://scdt.com/
