dbConfig:
    {
        client: 'mysql',
        connection:
            {
                host: '192.168.0.130',
                port: 3306,
                user: 'shortUrl',
                password: 'shortUrl',
                database: 'shortUrl',
            },
    }
