server:
  port: 8000

spring:
#  profiles:
#    include: dev-mongodb, dev-logging
  jackson:
    default-property-inclusion: non_null
knife4j:
  basic:
    enable: false #
    username: admin
    password: admin
